name: driver_app
description: Driver GPS tracking app for transport system.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.2.0
  geolocator: ^10.0.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
